<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Chapter [
	<!ATTLIST Chapter ChapterID CDATA #REQUIRED>
	<!ATTLIST Chapter ChapterName CDATA #REQUIRED>
	<!ELEMENT Chapter (Verse+)>
	<!ATTLIST Verse VerseID CDATA #REQUIRED>
	<!ELEMENT Verse (#PCDATA)>
]>
<!-- This SQL Query Generated at 03 February 2014 07:40 (UTC) from www.qurandatabase.org -->
<Chapter ChapterID="28" ChapterName="The Narrative">
	<Verse VerseID="1"><![CDATA[Ta. Sin. Mim.]]></Verse>
	<Verse VerseID="2"><![CDATA[These are Verses of the Book that makes (things) clear.]]></Verse>
	<Verse VerseID="3"><![CDATA[We rehearse to thee some of the story of Moses and Pharaoh in Truth, for people who believe.]]></Verse>
	<Verse VerseID="4"><![CDATA[Truly Pharaoh elated himself in the land and broke up its people into sections, depressing a small group among them: their sons he slew, but he kept alive their females: for he was indeed a maker of mischief.]]></Verse>
	<Verse VerseID="5"><![CDATA[And We wished to be Gracious to those who were being depressed in the land, to make them leaders (in Faith) and make them heirs,]]></Verse>
	<Verse VerseID="6"><![CDATA[To establish a firm place for them in the land, and to show Pharaoh, Haman, and their hosts, at their hands, the very things against which they were taking precautions.]]></Verse>
	<Verse VerseID="7"><![CDATA[So We sent this inspiration to the mother of Moses: "Suckle (thy child), but when thou hast fears about him, cast him into the river, but fear not nor grieve: for We shall restore him to thee, and We shall make him one of Our messengers."]]></Verse>
	<Verse VerseID="8"><![CDATA[Then the people of Pharaoh picked him up (from the river): (It was intended) that (Moses) should be to them an adversary and a cause of sorrow: for Pharaoh and Haman and (all) their hosts were men of sin.]]></Verse>
	<Verse VerseID="9"><![CDATA[The wife of Pharaoh said: "(Here is) joy of the eye, for me and for thee: slay him not. It may be that he will be use to us, or we may adopt him as a son." And they perceived not (what they were doing)!]]></Verse>
	<Verse VerseID="10"><![CDATA[But there came to be a void in the heart of the mother of Moses: She was going almost to disclose his (case), had We not strengthened her heart (with faith), so that she might remain a (firm) believer.]]></Verse>
	<Verse VerseID="11"><![CDATA[And she said to the sister of (Moses), "Follow him" so she (the sister) watched him in the character of a stranger. And they knew not.]]></Verse>
	<Verse VerseID="12"><![CDATA[And we ordained that he refused suck at first, until (His sister came up and) said: "Shall I point out to you the people of a house that will nourish and bring him up for you and be sincerely attached to him?"...]]></Verse>
	<Verse VerseID="13"><![CDATA[Thus did We restore him to his mother, that her eye might be comforted, that she might not grieve, and that she might know that the promise of Allah is true: but most of them do not understand.]]></Verse>
	<Verse VerseID="14"><![CDATA[When he reached full age, and was firmly established (in life), We bestowed on him wisdom and knowledge: for thus do We reward those who do good.]]></Verse>
	<Verse VerseID="15"><![CDATA[And he entered the city at a time when its people were not watching: and he found there two men fighting,- one of his own religion, and the other, of his foes. Now the man of his own religion appealed to him against his foe, and Moses struck him with his fist and made an end of him. He said: "This is a work of Evil (Satan): for he is an enemy that manifestly misleads!"]]></Verse>
	<Verse VerseID="16"><![CDATA[He prayed: "O my Lord! I have indeed wronged my soul! Do Thou then forgive me!" So (Allah) forgave him: for He is the Oft-Forgiving, Most Merciful.]]></Verse>
	<Verse VerseID="17"><![CDATA[He said: "O my Lord! For that Thou hast bestowed Thy Grace on me, never shall I be a help to those who sin!"]]></Verse>
	<Verse VerseID="18"><![CDATA[So he saw the morning in the city, looking about, in a state of fear, when behold, the man who had, the day before, sought his help called aloud for his help (again). Moses said to him: "Thou art truly, it is clear, a quarrelsome fellow!"]]></Verse>
	<Verse VerseID="19"><![CDATA[Then, when he decided to lay hold of the man who was an enemy to both of them, that man said: "O Moses! Is it thy intention to slay me as thou slewest a man yesterday? Thy intention is none other than to become a powerful violent man in the land, and not to be one who sets things right!"]]></Verse>
	<Verse VerseID="20"><![CDATA[And there came a man, running, from the furthest end of the City. He said: "O Moses! the Chiefs are taking counsel together about thee, to slay thee: so get thee away, for I do give thee sincere advice."]]></Verse>
	<Verse VerseID="21"><![CDATA[He therefore got away therefrom, looking about, in a state of fear. He prayed "O my Lord! save me from people given to wrong-doing."]]></Verse>
	<Verse VerseID="22"><![CDATA[Then, when he turned his face towards (the land of) Madyan, he said: "I do hope that my Lord will show me the smooth and straight Path."]]></Verse>
	<Verse VerseID="23"><![CDATA[And when he arrived at the watering (place) in Madyan, he found there a group of men watering (their flocks), and besides them he found two women who were keeping back (their flocks). He said: "What is the matter with you?" They said: "We cannot water (our flocks) until the shepherds take back (their flocks): And our father is a very old man."]]></Verse>
	<Verse VerseID="24"><![CDATA[So he watered (their flocks) for them; then he turned back to the shade, and said:"O my Lord! truly am I in (desperate) need of any good that Thou dost send me!"]]></Verse>
	<Verse VerseID="25"><![CDATA[Afterwards one of the (damsels) came (back) to him, walking bashfully. She said: "My father invites thee that he may reward thee for having watered (our flocks) for us." So when he came to him and narrated the story, he said: "Fear thou not: (well) hast thou escaped from unjust people."]]></Verse>
	<Verse VerseID="26"><![CDATA[Said one of the (damsels): "O my (dear) father! engage him on wages: truly the best of men for thee to employ is the (man) who is strong and trusty"....]]></Verse>
	<Verse VerseID="27"><![CDATA[He said: "I intend to wed one of these my daughters to thee, on condition that thou serve me for eight years; but if thou complete ten years, it will be (grace) from thee. But I intend not to place thee under a difficulty: thou wilt find me, indeed, if Allah wills, one of the righteous."]]></Verse>
	<Verse VerseID="28"><![CDATA[He said: "Be that (the agreement) between me and thee: whichever of the two terms I fulfil, let there be no ill-will to me. Be Allah a witness to what we say."]]></Verse>
	<Verse VerseID="29"><![CDATA[Now when Moses had fulfilled the term, and was travelling with his family, he perceived a fire in the direction of Mount Tur. He said to his family: "Tarry ye; I perceive a fire; I hope to bring you from there some information, or a burning firebrand, that ye may warm yourselves."]]></Verse>
	<Verse VerseID="30"><![CDATA[But when he came to the (fire), a voice was heard from the right bank of the valley, from a tree in hallowed ground: "O Moses! Verily I am Allah, the Lord of the Worlds....]]></Verse>
	<Verse VerseID="31"><![CDATA["Now do thou throw thy rod!" but when he saw it moving (of its own accord) as if it had been a snake, he turned back in retreat, and retraced not his steps: O Moses!" (It was said), "Draw near, and fear not: for thou art of those who are secure.]]></Verse>
	<Verse VerseID="32"><![CDATA["Move thy hand into thy bosom, and it will come forth white without stain (or harm), and draw thy hand close to thy side (to guard) against fear. Those are the two credentials from thy Lord to Pharaoh and his Chiefs: for truly they are a people rebellious and wicked."]]></Verse>
	<Verse VerseID="33"><![CDATA[He said: "O my Lord! I have slain a man among them, and I fear lest they slay me.]]></Verse>
	<Verse VerseID="34"><![CDATA["And my brother Aaron - He is more eloquent in speech than I: so send him with me as a helper, to confirm (and strengthen) me: for I fear that they may accuse me of falsehood."]]></Verse>
	<Verse VerseID="35"><![CDATA[He said: "We will certainly strengthen thy arm through thy brother, and invest you both with authority, so they shall not be able to touch you: with Our Sign shall ye triumph,- you two as well as those who follow you."]]></Verse>
	<Verse VerseID="36"><![CDATA[When Moses came to them with Our clear signs, they said: "This is nothing but sorcery faked up: never did we head the like among our fathers of old!"]]></Verse>
	<Verse VerseID="37"><![CDATA[Moses said: "My Lord knows best who it is that comes with guidance from Him and whose end will be best in the Hereafter: certain it is that the wrong-doers will not prosper."]]></Verse>
	<Verse VerseID="38"><![CDATA[Pharaoh said: "O Chiefs! no god do I know for you but myself: therefore, O Haman! light me a (kiln to bake bricks) out of clay, and build me a lofty palace, that I may mount up to the god of Moses: but as far as I am concerned, I think (Moses) is a liar!"]]></Verse>
	<Verse VerseID="39"><![CDATA[And he was arrogant and insolent in the land, beyond reason,- He and his hosts: they thought that they would not have to return to Us!]]></Verse>
	<Verse VerseID="40"><![CDATA[So We seized him and his hosts, and We flung them into the sea: Now behold what was the end of those who did wrong!]]></Verse>
	<Verse VerseID="41"><![CDATA[And we made them (but) leaders inviting to the Fire; and on the Day of Judgment no help shall they find.]]></Verse>
	<Verse VerseID="42"><![CDATA[in this world We made a curse to follow them and on the Day of Judgment they will be among the loathed (and despised).]]></Verse>
	<Verse VerseID="43"><![CDATA[We did reveal to Moses the Book after We had destroyed the earlier generations, (to give) Insight to men, and guidance and Mercy, that they might receive admonition.]]></Verse>
	<Verse VerseID="44"><![CDATA[Thou wast not on the Western side when We decreed the Commission to Moses, nor wast thou a witness (of those events).]]></Verse>
	<Verse VerseID="45"><![CDATA[But We raised up (new) generations, and long were the ages that passed over them; but thou wast not a dweller among the people of Madyan, rehearsing Our Signs to them; but it is We Who send messengers (with inspiration).]]></Verse>
	<Verse VerseID="46"><![CDATA[Nor wast thou at the side of (the Mountain of) Tur when we called (to Moses). Yet (art thou sent) as Mercy from thy Lord, to give warning to a people to whom no warner had come before thee: in order that they may receive admonition.]]></Verse>
	<Verse VerseID="47"><![CDATA[If (We had) not (sent thee to the Quraish),- in case a calamity should seize them for (the deeds) that their hands have sent forth, they might say: "Our Lord! why didst Thou not sent us a messenger? We should then have followed Thy Signs and been amongst those who believe!"]]></Verse>
	<Verse VerseID="48"><![CDATA[But (now), when the Truth has come to them from Ourselves, they say, "Why are not (Signs) sent to him, like those which were sent to Moses?" Do they not then reject (the Signs) which were formerly sent to Moses? They say: "Two kinds of sorcery, each assisting the other!" And they say: "For us, we reject all (such things)!"]]></Verse>
	<Verse VerseID="49"><![CDATA[Say: "Then bring ye a Book from Allah, which is a better guide than either of them, that I may follow it! (do), if ye are truthful!"]]></Verse>
	<Verse VerseID="50"><![CDATA[But if they hearken not to thee, know that they only follow their own lusts: and who is more astray than one who follow his own lusts, devoid of guidance from Allah? for Allah guides not people given to wrong-doing.]]></Verse>
	<Verse VerseID="51"><![CDATA[Now have We caused the Word to reach them themselves, in order that they may receive admonition.]]></Verse>
	<Verse VerseID="52"><![CDATA[Those to whom We sent the Book before this,- they do believe in this (revelation):]]></Verse>
	<Verse VerseID="53"><![CDATA[And when it is recited to them, they say: "We believe therein, for it is the Truth from our Lord: indeed we have been Muslims (bowing to Allah´s Will) from before this.]]></Verse>
	<Verse VerseID="54"><![CDATA[Twice will they be given their reward, for that they have persevered, that they avert Evil with Good, and that they spend (in charity) out of what We have given them.]]></Verse>
	<Verse VerseID="55"><![CDATA[And when they hear vain talk, they turn away therefrom and say: "To us our deeds, and to you yours; peace be to you: we seek not the ignorant."]]></Verse>
	<Verse VerseID="56"><![CDATA[It is true thou wilt not be able to guide every one, whom thou lovest; but Allah guides those whom He will and He knows best those who receive guidance.]]></Verse>
	<Verse VerseID="57"><![CDATA[They say: "If we were to follow the guidance with thee, we should be snatched away from our land." Have We not established for them a secure sanctuary, to which are brought as tribute fruits of all kinds,- a provision from Ourselves? but most of them understand not.]]></Verse>
	<Verse VerseID="58"><![CDATA[And how many populations We destroyed, which exulted in their life (of ease and plenty)! now those habitations of theirs, after them, are deserted,- All but a (miserable) few! and We are their heirs!]]></Verse>
	<Verse VerseID="59"><![CDATA[Nor was thy Lord the one to destroy a population until He had sent to its centre a messenger, rehearsing to them Our Signs; nor are We going to destroy a population except when its members practise iniquity.]]></Verse>
	<Verse VerseID="60"><![CDATA[The (material) things which ye are given are but the conveniences of this life and the glitter thereof; but that which is with Allah is better and more enduring: will ye not then be wise?]]></Verse>
	<Verse VerseID="61"><![CDATA[Are (these two) alike?- one to whom We have made a goodly promise, and who is going to reach its (fulfilment), and one to whom We have given the good things of this life, but who, on the Day of Judgment, is to be among those brought up (for punishment)?]]></Verse>
	<Verse VerseID="62"><![CDATA[That Day (Allah) will call to them, and say "Where are my ´partners´?- whom ye imagined (to be such)?"]]></Verse>
	<Verse VerseID="63"><![CDATA[Those against whom the charge will be proved, will say: "Our Lord! These are the ones whom we led astray: we led them astray, as we were astray ourselves: we free ourselves (from them) in Thy presence: it was not us they worshipped."]]></Verse>
	<Verse VerseID="64"><![CDATA[It will be said (to them): "Call upon your ´partners´ (for help)" :they will call upon them, but they will not listen to them; and they will see the Penalty (before them); (how they will wish) ´if only they had been open to guidance!´]]></Verse>
	<Verse VerseID="65"><![CDATA[That Day (Allah) will call to them, and say: "What was the answer ye gave to the messengers?"]]></Verse>
	<Verse VerseID="66"><![CDATA[Then the (whole) story that Day will seem obscure to them (like light to the blind) and they will not be able (even) to question each other.]]></Verse>
	<Verse VerseID="67"><![CDATA[But any that (in this life) had repented, believed, and worked righteousness, will have hopes to be among those who achieve salvation.]]></Verse>
	<Verse VerseID="68"><![CDATA[Thy Lord does create and choose as He pleases: no choice have they (in the matter): Glory to Allah! and far is He above the partners they ascribe (to Him)!]]></Verse>
	<Verse VerseID="69"><![CDATA[And thy Lord knows all that their hearts conceal and all that they reveal.]]></Verse>
	<Verse VerseID="70"><![CDATA[And He is Allah: There is no god but He. To Him be praise, at the first and at the last: for Him is the Command, and to Him shall ye (all) be brought back.]]></Verse>
	<Verse VerseID="71"><![CDATA[Say: See ye? If Allah were to make the night perpetual over you to the Day of Judgment, what god is there other than Allah, who can give you enlightenment? Will ye not then hearken?]]></Verse>
	<Verse VerseID="72"><![CDATA[Say: See ye? If Allah were to make the day perpetual over you to the Day of Judgment, what god is there other than Allah, who can give you a night in which ye can rest? Will ye not then see?]]></Verse>
	<Verse VerseID="73"><![CDATA[It is out of His Mercy that He has made for you Night and Day,- that ye may rest therein, and that ye may seek of his Grace;- and in order that ye may be grateful.]]></Verse>
	<Verse VerseID="74"><![CDATA[The Day that He will call on them, He will say: "Where are my ´partners´? whom ye imagined (to be such)?"]]></Verse>
	<Verse VerseID="75"><![CDATA[And from each people shall We draw a witness, and We shall say: "Produce your Proof": then shall they know that the Truth is in Allah (alone), and the (lies) which they invented will leave them in lurch.]]></Verse>
	<Verse VerseID="76"><![CDATA[Qarun was doubtless, of the people of Moses; but he acted insolently towards them: such were the treasures We had bestowed on him that their very keys would have been a burden to a body of strong men, behold, his people said to him: "Exult not, for Allah loveth not those who exult (in riches).]]></Verse>
	<Verse VerseID="77"><![CDATA["But seek, with the (wealth) which Allah has bestowed on thee, the Home of the Hereafter, nor forget thy portion in this world: but do thou good, as Allah has been good to thee, and seek not (occasions for) mischief in the land: for Allah loves not those who do mischief."]]></Verse>
	<Verse VerseID="78"><![CDATA[He said: "This has been given to me because of a certain knowledge which I have." Did he not know that Allah had destroyed, before him, (whole) generations,- which were superior to him in strength and greater in the amount (of riches) they had collected? but the wicked are not called (immediately) to account for their sins.]]></Verse>
	<Verse VerseID="79"><![CDATA[So he went forth among his people in the (pride of his wordly) glitter. Said those whose aim is the Life of this World: "Oh! that we had the like of what Qarun has got! for he is truly a lord of mighty good fortune!"]]></Verse>
	<Verse VerseID="80"><![CDATA[But those who had been granted (true) knowledge said: "Alas for you! The reward of Allah (in the Hereafter) is best for those who believe and work righteousness: but this none shall attain, save those who steadfastly persevere (in good)."]]></Verse>
	<Verse VerseID="81"><![CDATA[Then We caused the earth to swallow up him and his house; and he had not (the least little) party to help him against Allah, nor could he defend himself.]]></Verse>
	<Verse VerseID="82"><![CDATA[And those who had envied his position the day before began to say on the morrow: "Ah! it is indeed Allah Who enlarges the provision or restricts it, to any of His servants He pleases! had it not been that Allah was gracious to us, He could have caused the earth to swallow us up! Ah! those who reject Allah will assuredly never prosper."]]></Verse>
	<Verse VerseID="83"><![CDATA[That Home of the Hereafter We shall give to those who intend not high-handedness or mischief on earth: and the end is (best) for the righteous.]]></Verse>
	<Verse VerseID="84"><![CDATA[If any does good, the reward to him is better than his deed; but if any does evil, the doers of evil are only punished (to the extent) of their deeds.]]></Verse>
	<Verse VerseID="85"><![CDATA[Verily He Who ordained the Qur´an for thee, will bring thee back to the Place of Return. Say: "My Lord knows best who it is that brings true guidance, and who is in manifest error."]]></Verse>
	<Verse VerseID="86"><![CDATA[And thou hadst not expected that the Book would be sent to thee except as a Mercy from thy Lord: Therefore lend not thou support in any way to those who reject (Allah´s Message).]]></Verse>
	<Verse VerseID="87"><![CDATA[And let nothing keep thee back from the Signs of Allah after they have been revealed to thee: and invite (men) to thy Lord, and be not of the company of those who join gods with Allah.]]></Verse>
	<Verse VerseID="88"><![CDATA[And call not, besides Allah, on another god. There is no god but He. Everything (that exists) will perish except His own Face. To Him belongs the Command, and to Him will ye (all) be brought back.]]></Verse>
</Chapter>
